FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime

WORKDIR /app
COPY . /app
RUN python -m pip install --upgrade pip && python -m pip install -e ".[dev,triton]"
CMD ["python", "-m", "pytest", "-m", "gpu or triton"]
